### ISSUE TITLE
偏移量怎么获取到的呢

### ISSUE THREAD

**Issue by a719724508** [shenhunluo/wx_dump_rs#4]
# 获取key的偏移量
target\release\wx_dump_rs.exe search -s "你的key" --encode hex --from-all-data --real-addr
没有看明白这个key应该从哪里获取到

**Comment by shenhunluo** [comment]
> # 获取key的偏移量
> target\release\wx_dump_rs.exe search -s "你的key" --encode hex --from-all-data --real-addr
> 没有看明白这个key应该从哪里获取到

要已知key才能找地址，有地址了程序才能找到key。鸡和蛋你至少得有一个。
不过key所有版本的都一样，地址在所有电脑上都一样，所以怎么用你就自由发挥了

**Comment by a719724508** [comment]
> > # 获取key的偏移量
> > target\release\wx_dump_rs.exe search -s "你的key" --encode hex --from-all-data --real-addr
> > 没有看明白这个key应该从哪里获取到
> 
> 要已知key才能找地址，有地址了程序才能找到key。鸡和蛋你至少得有一个。 不过key所有版本的都一样，地址同一版本在所有电脑上都一样，所以怎么用你就自由发挥了
明白了，感谢大神
